[15.0][MIG]hr_expense_cancel
OCA/hr-expense pull request #112
Opened 2022-04-26 09:43 UTC by manuelregidor

Standard migration.

2022-04-26 09:45 UTC, manuelregidor commented
@HaraldPanten @ValentinVinagre

2022-04-26 10:07 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2022-04-26 13:15 UTC, HaraldPanten requested changes
Hi @manuelregidor 

I think it's not a standard migration, as you've applied some changes in order to adapt the module to make it more compatible with the standard "Cancel" button from V15.

Could you, please:

- Adapt the README file.
- Explain in a comment (here in github, not in the readme file) the changes from V14 to V15for this module. (screenshots are welcome).

After that we can mention the repository PSCs and ask them about their opinion for these changes.

THX!

2022-04-27 07:53 UTC, HaraldPanten approved these changes
Functional review

2022-04-27 07:54 UTC, HaraldPanten commented
@pedrobaeza @ivantodorovich Could you have a quick look at this one?

2022-04-27 11:14 UTC, ivantodorovich approved these changes
LG

2022-04-27 11:14 UTC, ivantodorovich commented on hr_expense_cancel/models/hr_expense.py
> +                account_move.with_context(**{"force_delete": True}).unlink()
Just use `account_move.with_context(force_delete=True).unlink()`

2022-04-27 11:29 UTC, manuelregidor commented on hr_expense_cancel/models/hr_expense.py
> +                account_move.with_context(**{"force_delete": True}).unlink()
Done

2022-04-28 09:23 UTC, Saran440 commented
Hello All, Should you review  this PR: https://github.com/OCA/hr-expense/pull/56 before migrate to V15?
I found it will conflict with standard odoo.

2022-04-28 09:38 UTC, HaraldPanten commented
Hi @Saran440 thx for your comments.

As it's an enhancement, I'd leave that for later (after migration).

For us, having a "gap" in this journal entries sequence (momently) because of cancelling the expenses, hasn't been any problem. As we solve it later.

It's the same when you delete an account move (invoice). You have to consider the sequence as well.

WDYT?

2022-05-02 18:04 UTC, HaraldPanten commented
@pedrobaeza Could you merge, please?

THX!

2022-05-02 18:05 UTC, pedrobaeza commented
No review by my part

/ocabot migration hr_expense_cancel
/ocabot merge nobump

2022-05-02 18:11 UTC, merged

2022-05-02 18:14 UTC, HaraldPanten commented
THX!

2022-05-04 04:46 UTC, Saran440 commented
@HaraldPanten Sorry for late.
Okay, I will do it later if it helpful with module.

2022-05-04 06:39 UTC, HaraldPanten commented
> 

No problem, Just ping me once you make the PR and I'll review 👍