[14.0][FIX] hr_expense_invoice: use bill partner in expense journal item when expense paid by company
OCA/hr-expense pull request #192
Opened 2023-07-16 15:00 UTC by JordiBForgeFlow

If the expense is paid by the company and the expense refers to a bill, then the company will receive charge in the company account from the vendor, not from the employee.

In addition, when the expense is paid by the company the bill should be paid (reconciled), because the expense creates an outstanding payment line, to be reconciled later in the company bank account reconciliation process.

cc @victoralmau @pedrobaeza

2023-07-19 12:59 UTC, pedrobaeza commented
> If the expense is paid by the company and the expense refers to a bill, then the company will receive charge in the company account from the vendor, not from the employee.

Please indicate visually what you refer.

> In addition, when the expense is paid by the company the bill should be paid (reconciled), because the expense creates an outstanding payment line, to be reconciled later in the company bank account reconciliation process.

This module intercepts the move creation, and uses the bill one as target, so I don't understand what you want to get.

2023-11-27 10:08 UTC, victoralmau reviewed
This seems to make sense.

2023-11-27 10:08 UTC, victoralmau approved these changes
This seems to make sense.

2023-11-27 19:20 UTC, pedrobaeza requested changes

2023-11-27 19:20 UTC, pedrobaeza commented on hr_expense_invoice/tests/test_hr_expense_invoice.py
> +        self.assertEqual(self.invoice.payment_state, "paid")
**issue:** Why this check has been changed?

2023-11-27 19:20 UTC, pedrobaeza commented on hr_expense_invoice/models/hr_expense_sheet.py
> +                    and x.account_id.internal_type == "payable"
**question:** Why this change?

2023-12-09 19:16 UTC, rafaelbn approved these changes
Thank you! 👍🏼 

Actually this is an issue since Odoo change in 14 outstanding payment management

@JordiBForgeFlow if you can rebase I could record a video to explain the change in runboat

😄

2024-05-19 12:11 UTC, closed without merging