[14.0] [NEW] hr_expense_analytic_distribution: New module to distribute the expenses into various analytic account.
OCA/hr-expense pull request #27
Opened 2021-01-29 10:47 UTC by Chandresh-OSI

2021-01-30 13:14 UTC, Saran440 commented
Functional Test. I have question
1. If we don't access right Analytic Account. Should we can do this module?
2. we would be distribute to analytic 20% and and expense normal process 80%. Is it possible?
if not, you should constain total distribute must be 100

2021-01-30 14:00 UTC, pedrobaeza commented
Why not using analytic distributions from tags?

2021-02-02 09:47 UTC, dreispt commented
@Saran440 
1. Right no, no, you need at least to be able to select Analytic Account. But it would be simple to add that permission here.
2. It would be possible, but IMO error prone. I would prefer to require users to proves a 100% total distribution.

@pedrobaeza 
That was tested but doesn't work for the EE Finance Reports, such as P&L.
They basically ignore analytic tag distribution.

2021-02-02 10:05 UTC, dreispt requested changes

2021-02-02 10:05 UTC, dreispt commented on hr_expense_analytic_distribution/models/hr_expense_sheet.py
> +                    raise UserError(_("Sorry, Percentage should be equal to 100."))
Don't do validations in a computation.
Use a contrains method instead.

2021-02-02 10:05 UTC, dreispt commented on hr_expense_analytic_distribution/models/hr_expense_sheet.py
> +    count_percent = fields.Float(compute="_compute_count_percent")
Names are important. This is not a count, it is a sum or a total.
Actually, I don't think we even need this field.

2021-02-02 10:05 UTC, dreispt commented on hr_expense_analytic_distribution/models/hr_expense_sheet.py
> +            rec.count_percent = 100 - percent
```suggestion
    @api.constrains("expense_distribution_ids.percentage")
    def _constrains_distribution_ids_percentage(self):
        for report in self:
            total_percent = sum(report.expense_distribution_ids.mapped("percentage")
            if total_percent != 100:
                    raise UserError(_("Sorry, Percentage should be equal to 100."))
```

2021-02-02 10:05 UTC, dreispt commented on hr_expense_analytic_distribution/models/hr_expense.py
> +    def _get_account_move_line_values(self):
The right way to do this is to call super() and get the result.
Then work on that data structure, copying and modifying the line data to perform the distribution.
Not using super() breaks the inheritance chain.

2021-02-02 10:05 UTC, dreispt commented on hr_expense_analytic_distribution/models/hr_expense.py
> +    def _get_account_move_line_values(self):
I would love to see this implemented in under 40-50 LoC

2021-02-02 10:33 UTC, pedrobaeza commented
@dreispt financial reports has nothing to do with this. I'm talking about adding to the expense tags with distribution, and make them to generate analytic entries.

2021-02-02 12:01 UTC, dreispt commented
@pedrobaeza Yes, ff you don't care about the financial reports, that works and you don't need this feature.
In my case, I expect to be able to analyze the P&L by Analytic Account, and Analytic Tags don't work for that.

2021-02-02 12:04 UTC, pedrobaeza commented
Yes, but I'm not talking about that. I'm talking about not reinventing a new model for reflecting distributions: use tags model, but do the same split over accounting entries.

2021-02-02 12:16 UTC, dreispt commented
@pedrobaeza I see your point.

We expect distribution to be different in most expense reports.
So the UX would be either:
a) have the user search Tags for an existing one, and create one if if doesn't exist. This is hard for basic expense users.
b) create a tag for each expense report. This would pollute the tags list, in case they are being used for other purposes. 

The above the UX inconveniences made me prefer a manual distribution for each expense report.
What do you think?

2021-02-02 12:18 UTC, pedrobaeza commented
OK, I got as well your point. Maybe you can do the following: on the distribution part, allow to select an analytic tag with distribution, and on such onchange, populate your distribution lines with such information. So you get the best of both worlds, having the option to use "templates" for distributions, or create them manually.

2021-02-02 12:33 UTC, dreispt commented
@pedrobaeza That sounds nice, but It is really two feature working together, and I don't want to implement the two.
I could extend the Tag to also impact Accounting Moves, and always use a Tag on the Expense Report, that could easily be created on the fly. That solves the Expense Report UX.

I worry that:
a) the additional Account Move splits on Tags would have collateral effects on other usages of it, and 
b) the big number of Tags this process would create.

There are ways to mitigate b), like creating archived entries, or use a flag filter.
Is a) something to worry about?

2021-02-02 12:37 UTC, pedrobaeza commented
I think you haven't understood me: I'm only proposing to have a field tags to act as template for your distribution, isolated from any other tag use, but anyway, don't worry if you don't want to implement this. It was just a suggestion, but not real case for me for now.

2021-02-02 12:53 UTC, dreispt commented
I see - the actual split logic would still be independent from Tags.
That is a good suggestion, I'll keep it in mind, it could be an enhancement if the template use case is brought to the table.
Thank you Pedro.

2021-02-11 16:54 UTC, dreispt approved these changes
I code reviewed, and in the process added tests and streamlined the business logic.

2021-03-18 11:38 UTC, dreispt commented
/ocabot merge nobump

2021-04-06 10:14 UTC, dreispt commented
/ocabot merge nobump

2021-04-06 10:17 UTC, merged