[18.0][MIG] hr_expense_employee_analytic_default: Migration to 18.0
OCA/hr-expense pull request #283
Opened 2024-12-27 10:56 UTC by HeliconiaSolutions

2025-01-17 10:42 UTC, Saran440 commented
/ocabot migration hr_expense_employee_analytic_default

2025-01-17 17:46 UTC, marcelsavegnago approved these changes
LGTM

2025-05-21 16:38 UTC, CRogos reviewed
Code LGTM.


> 3.  When changing the employee, the analytical distribution will
>     be updated.
When changing to a product, where no analytic distribution exists, the analytic accounts are not removed but stay with the previous distribution.

I've also tried to set a distribution for Partner "Anita Oliver", but when I select the employee "Anita Oliver" the distribution is not applied.

2025-09-23 15:42 UTC, CRogos commented
@BhaveshHeliconia same findings like before. Did you change anything or just a rebase?

2025-09-24 06:24 UTC, BhaveshHeliconia commented
@CRogos : Earlier I had only rebased, but now I’ve also updated the README file.

2025-09-24 06:51 UTC, CRogos commented
I agree with the readme change, but changing the employee did not work, and also the analytic distribution did not get removed, when I change to a product without distribution template.

2025-09-24 07:35 UTC, BhaveshHeliconia commented
> I agree with the readme change, but changing the employee did not work, and also the analytic distribution did not get removed, when I change to a product without distribution template.

Okay, I’ll work on fixing that.

2026-03-10 06:53 UTC, BhaveshHeliconia commented
@CRogos : The module now updates and clears the analytic distribution as expected when changing the employee or product, both interactively and on save. I have also added test cases for the onchange logic.
Could you please review it when you get a chance? Thanks in advance.

2026-03-10 11:34 UTC, CristianoMafraJunior approved these changes
LGTM

2026-03-10 13:49 UTC, CRogos reviewed
@BhaveshHeliconia we are currently not using this module. Therefore I am not really into it and my first test failed, most likely because I did not set the work_contact_id correct.

2026-04-06 08:14 UTC, BhaveshHeliconia commented
@victoralmau could you please review this module when you get a chance? Thank you in advance!

2026-04-06 08:42 UTC, victoralmau requested changes

2026-04-06 08:42 UTC, victoralmau commented on hr_expense_employee_analytic_default/models/account_analytic_distribution_model.py
> -            if employee.address_id:
I don't understand why this field was changed and a different one is now being used; in my opinion, it would be better to use `address_id`.

2026-04-06 08:42 UTC, victoralmau commented on hr_expense_employee_analytic_default/models/hr_expense.py
> +            self.analytic_distribution = {}
In my opinion, this `onchange` method is unnecessary; the `_compute_analytic_distribution()` method already adds the appropriate context `hr_expense_employee_id` to define the corresponding analytical distribution. For this reason, the `_get_distribution()` method uses the appropriate context value to perform the necessary actions there.

2026-04-06 09:22 UTC, BhaveshHeliconia commented on hr_expense_employee_analytic_default/models/account_analytic_distribution_model.py
> -            if employee.address_id:
Actually address_id is the company work address — it's computed from company_id.partner_id, so all employees in the same company end up with the same address_id. That wouldn't work here since we need to match distribution rules per employee.

If you check Odoo core's _compute_analytic_distribution() in hr_expense.py (L522-523), it also uses work_contact_id for the partner matching. So we're staying consistent with how core handles it.

2026-04-06 09:22 UTC, BhaveshHeliconia commented on hr_expense_employee_analytic_default/models/hr_expense.py
> +            self.analytic_distribution = {}
you're right. The _compute_analytic_distribution() already depends on employee_id and product_id, and the context override we add takes care of the rest through _get_distribution(). The onchange is just duplicating that logic. I'll remove it and update the tests.

2026-04-06 09:52 UTC, victoralmau requested changes
Reviewing hr_expense in v18 https://github.com/odoo/odoo/blob/ffba9eb97876c2507f3bc137298388bf96db6b16/addons/hr_expense/models/hr_expense. py#L522, the appropriate `partner_id` (the employee's) is already defined; therefore, this module would no longer be necessary because `hr_expense` already does the same thing.

2026-04-06 09:59 UTC, BhaveshHeliconia commented
> Reviewing hr_expense in v18 https://github.com/odoo/odoo/blob/ffba9eb97876c2507f3bc137298388bf96db6b16/addons/hr_expense/models/hr_expense. py#L522, the appropriate `partner_id` (the employee's) is already defined; therefore, this module would no longer be necessary because `hr_expense` already does the same thing.

You're right, I checked and in v16 the _compute_analytic_distribution didn't consider the employee at all — no partner_id or employee_id in the depends or vals. That's why this module was needed back then. But in v18 they added employee_id as a dependency and pass work_contact_id as the partner_id directly, so the core now does exactly what this module was doing. It looks like this module is no longer needed for v18.

2026-04-07 09:48 UTC, MiquelRForgeFlow commented
Then please close the PR.

2026-04-07 09:57 UTC, closed without merging